@echo off
setlocal
cd /d "%~dp0"

rem ============================================================
rem  Project Doctor
rem  Generated by Venv Batch Template Generator v3.3
rem  Generated on: 2026-06-21 23:54
rem ============================================================

set "PROJECT_NAME=creep"
set "VENV_DIR=.venv"
set "ENTRY_MODE=file"
set "APP_ENTRY=creep_gui.py"
set "RUNNER_ARGS="
set "PY=%CD%\%VENV_DIR%\Scripts\python.exe"

echo ============================================================
echo  PROJECT DOCTOR: %PROJECT_NAME%
echo ============================================================
echo  Project : %CD%
echo  Mode    : %ENTRY_MODE%
echo  Entry   : %APP_ENTRY%
if /I "%ENTRY_MODE%"=="runner" echo  Args    : %RUNNER_ARGS%
echo.

if not exist "%PY%" (
    echo [FAIL] venv not found at: "%PY%"
    echo.
    echo Create it with:
    echo   python -m venv "%VENV_DIR%"
    pause
    exit /b 1
)

echo [OK] venv found: "%PY%"
echo.

echo ------------------------------------------------------------
echo  Python Environment
echo ------------------------------------------------------------
"%PY%" -c "import sys; print('Executable :', sys.executable); print('Version    :', sys.version.split()[0]); print('Prefix     :', sys.prefix)"
echo.

echo ------------------------------------------------------------
echo  pip version
echo ------------------------------------------------------------
"%PY%" -m pip --version
echo.

echo ------------------------------------------------------------
echo  Installed Packages
echo ------------------------------------------------------------
"%PY%" -m pip list
echo.

echo ------------------------------------------------------------
echo  Dependency Health
echo ------------------------------------------------------------
"%PY%" -m pip check
echo.

echo ------------------------------------------------------------
echo  Entry Point Check
echo ------------------------------------------------------------
if /I "%ENTRY_MODE%"=="file" (
    if exist "%APP_ENTRY%" (
        echo [OK] Entry file found: "%APP_ENTRY%"
    ) else (
        echo [FAIL] Entry file NOT found: "%APP_ENTRY%"
    )
) else (
    "%PY%" -c "import importlib.util, sys; name=r'%APP_ENTRY%'; spec=importlib.util.find_spec(name); print(('[OK] Module found: ' if spec else '[FAIL] Module NOT found: ') + name); sys.exit(0 if spec else 1)" 2>nul
    if errorlevel 1 echo [FAIL] Module import test failed.
    if /I "%ENTRY_MODE%"=="runner" echo [INFO] Runner args: "%RUNNER_ARGS%"
)
echo.

echo ------------------------------------------------------------
echo  Project Files
echo ------------------------------------------------------------
if exist "uv.lock"          echo [OK]   uv.lock found
if exist "pyproject.toml"   echo [OK]   pyproject.toml found
if exist "requirements.txt" echo [OK]   requirements.txt found
if not exist "requirements.txt" echo [WARN] requirements.txt missing

echo.

echo ============================================================
echo  DOCTOR COMPLETE
echo ============================================================
pause
exit /b 0
