@echo off
setlocal
cd /d "%~dp0"

rem ============================================================
rem  Project-local pip wrapper
rem  Generated by Venv Batch Template Generator v3.3
rem  Generated on: 2026-06-21 23:54
rem
rem  Usage:
rem    pip.bat install requests
rem    pip.bat install -r requirements.txt
rem    pip.bat freeze > requirements.txt
rem    pip.bat list
rem    pip.bat uninstall requests
rem ============================================================

set "VENV_DIR=.venv"
set "PY=%CD%\%VENV_DIR%\Scripts\python.exe"

if not exist "%PY%" (
    echo [ERROR] Local venv was not found:
    echo         "%PY%"
    echo.
    echo Create it with:
    echo         python -m venv "%VENV_DIR%"
    echo.
    pause
    exit /b 1
)

"%PY%" -m pip %*
exit /b %ERRORLEVEL%
