@echo off
setlocal
cd /d "%~dp0"

rem ============================================================
rem  Project Setup
rem  Generated by Venv Batch Template Generator v3.3
rem  Generated on: 2026-06-21 23:54
rem
rem  Run this once to bootstrap the project environment.
rem  After setup, use run.bat to launch the project.
rem ============================================================

set "PROJECT_NAME=creep"
set "VENV_DIR=.venv"

title "%PROJECT_NAME% - SETUP"

echo ============================================================
echo  Setting up: %PROJECT_NAME%
echo ============================================================
echo.

where python >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python is not installed or not on PATH.
    echo.
    echo Install Python from https://www.python.org/downloads/
    echo Make sure to check "Add Python to PATH" during installation.
    echo.
    pause
    exit /b 1
)

if exist "%VENV_DIR%\Scripts\python.exe" (
    echo [INFO] Virtual environment already exists at "%VENV_DIR%\"
    echo        Delete it first to re-run setup.
    echo.
    pause
    exit /b 0
)

echo [1/3] Creating virtual environment...
echo ============================================================
python -m venv "%VENV_DIR%"
echo.

echo [2/3] Upgrading pip...
echo ============================================================
"%VENV_DIR%\Scripts\python.exe" -m pip install --upgrade pip
echo.

if exist "requirements.txt" (
    echo [3/3] Installing dependencies from requirements.txt...
    echo ============================================================
    "%VENV_DIR%\Scripts\python.exe" -m pip install -r requirements.txt
    echo.
) else (
    echo [3/3] SKIPPED: No requirements.txt found.
    echo        Add dependencies then run sync.bat to install them.
    echo.
)

echo ============================================================
echo  SETUP COMPLETE
echo  Run run.bat to launch the project.
echo ============================================================
pause
exit /b 0
