@echo off
setlocal EnableDelayedExpansion
cd /d "%~dp0"

rem ============================================================
rem  Project Setup  [self-unpacking]
rem  Generated by Venv Batch Template Generator v3.3
rem
rem  Ship only this file. Run it once to:
rem    1. Check Python
rem    2. Create / verify the virtual environment
rem    3. Install dependencies from requirements.txt
rem    4. Write companion scripts (run / pip / sync / shell /
rem       test / doctor) beside this file
rem ============================================================

set "PROJECT_NAME=creep"
set "VENV_DIR=.venv"
set "ENTRY_MODE=file"
set "APP_ENTRY=creep_gui.py"
set "RUNNER_ARGS="

title "%PROJECT_NAME% - SETUP"

echo ============================================================
echo  Setting up: %PROJECT_NAME%
echo ============================================================
echo.

rem ── 1. Python check ─────────────────────────────────────────
where python >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python is not installed or not on PATH.
    echo.
    echo Install Python from https://www.python.org/downloads/
    echo Make sure to check "Add Python to PATH" during installation.
    echo.
    pause
    exit /b 1
)

rem ── 2. Venv ─────────────────────────────────────────────────
if exist "%VENV_DIR%\Scripts\python.exe" (
    echo [INFO] Virtual environment already exists at "%VENV_DIR%\"
    echo        Skipping creation.
    echo.
) else (
    echo [1/3] Creating virtual environment...
    echo ============================================================
    python -m venv "%VENV_DIR%"
    if errorlevel 1 (
        echo [ERROR] Failed to create virtual environment.
        pause
        exit /b 1
    )
    echo.

    echo [2/3] Upgrading pip...
    echo ============================================================
    "%VENV_DIR%\Scripts\python.exe" -m pip install --upgrade pip
    echo.

    if exist "requirements.txt" (
        echo [3/3] Installing dependencies from requirements.txt...
        echo ============================================================
        "%VENV_DIR%\Scripts\python.exe" -m pip install -r requirements.txt
        echo.
    ) else (
        echo [3/3] SKIPPED: No requirements.txt found.
        echo        Add dependencies then run sync.bat to install them.
        echo.
    )
)

rem ── 3. Write companion scripts ───────────────────────────────
echo ============================================================
echo  Writing companion scripts...
echo ============================================================
echo.

rem ── run.bat ──────────────────────────────────────────────────
if exist "run.bat" (
    echo [SKIP] run.bat already exists
) else (
(
echo @echo off
echo setlocal EnableDelayedExpansion
echo cd /d "%%~dp0"
echo.
echo rem ============================================================
echo rem  Project Runner
echo rem  Generated by setup.bat
echo rem ============================================================
echo.
echo set "PROJECT_NAME=%PROJECT_NAME%"
echo set "VENV_DIR=%VENV_DIR%"
echo set "ENTRY_MODE=%ENTRY_MODE%"
echo set "APP_ENTRY=%APP_ENTRY%"
echo set "RUNNER_ARGS=%RUNNER_ARGS%"
echo.
echo set "PY=%%CD%%\%%VENV_DIR%%\Scripts\python.exe"
echo.
echo if not exist "%%PY%%" ^(
echo     echo [ERROR] Local venv not found: "%%PY%%"
echo     echo.
echo     echo Fix with:
echo     echo   python -m venv "%%VENV_DIR%%"
echo     echo   "%%VENV_DIR%%\Scripts\python.exe" -m pip install --upgrade pip
echo     echo   "%%VENV_DIR%%\Scripts\python.exe" -m pip install -r requirements.txt
echo     echo.
echo     pause
echo     exit /b 1
echo ^)
echo.
echo if /I "%%ENTRY_MODE%%"=="file" if not exist "%%APP_ENTRY%%" ^(
echo     echo [ERROR] Entry file not found: "%%APP_ENTRY%%"
echo     echo Edit run.bat or run with the correct entry file.
echo     pause
echo     exit /b 1
echo ^)
echo.
echo title "%%PROJECT_NAME%% - RUN"
echo echo ============================================================
echo echo  Running : %%PROJECT_NAME%%
echo echo  Project : %%CD%%
echo echo  Python  : %%PY%%
echo echo  Mode    : %%ENTRY_MODE%%
echo echo  Entry   : %%APP_ENTRY%%
echo if /I "%%ENTRY_MODE%%"=="runner" echo  Args    : %%RUNNER_ARGS%%
echo echo ============================================================
echo echo.
echo.
echo set "EXITCODE=0"
echo.
echo if /I "%%ENTRY_MODE%%"=="module" ^(
echo     "%%PY%%" -m %%APP_ENTRY%% %%*
echo ^) else if /I "%%ENTRY_MODE%%"=="runner" ^(
echo     if defined RUNNER_ARGS ^(
echo         "%%PY%%" -m %%APP_ENTRY%% !RUNNER_ARGS! %%*
echo     ^) else ^(
echo         "%%PY%%" -m %%APP_ENTRY%% %%*
echo     ^)
echo ^) else ^(
echo     "%%PY%%" "%%APP_ENTRY%%" %%*
echo ^)
echo.
echo set "EXITCODE=!ERRORLEVEL!"
echo.
echo echo.
echo echo ============================================================
echo echo  Process exited with code: !EXITCODE!
echo echo ============================================================
echo pause
echo exit /b !EXITCODE!
) > run.bat
    echo [OK]   run.bat
)

rem ── pip.bat ──────────────────────────────────────────────────
if exist "pip.bat" (
    echo [SKIP] pip.bat already exists
) else (
(
echo @echo off
echo setlocal
echo cd /d "%%~dp0"
echo.
echo rem ============================================================
echo rem  Project-local pip wrapper
echo rem  Generated by setup.bat
echo rem.
echo rem  Usage:
echo rem    pip.bat install requests
echo rem    pip.bat install -r requirements.txt
echo rem    pip.bat freeze ^> requirements.txt
echo rem    pip.bat list
echo rem    pip.bat uninstall requests
echo rem ============================================================
echo.
echo set "VENV_DIR=%VENV_DIR%"
echo set "PY=%%CD%%\%%VENV_DIR%%\Scripts\python.exe"
echo.
echo if not exist "%%PY%%" ^(
echo     echo [ERROR] Local venv was not found:
echo     echo         "%%PY%%"
echo     echo.
echo     echo Create it with:
echo     echo         python -m venv "%%VENV_DIR%%"
echo     echo.
echo     pause
echo     exit /b 1
echo ^)
echo.
echo "%%PY%%" -m pip %%*
echo exit /b %%ERRORLEVEL%%
) > pip.bat
    echo [OK]   pip.bat
)

rem ── sync.bat ─────────────────────────────────────────────────
if exist "sync.bat" (
    echo [SKIP] sync.bat already exists
) else (
(
echo @echo off
echo setlocal
echo cd /d "%%~dp0"
echo.
echo rem ============================================================
echo rem  Dependency Sync
echo rem  Generated by setup.bat
echo rem ============================================================
echo.
echo set "PROJECT_NAME=%PROJECT_NAME%"
echo set "VENV_DIR=%VENV_DIR%"
echo set "PY=%%CD%%\%%VENV_DIR%%\Scripts\python.exe"
echo.
echo if not exist "%%PY%%" ^(
echo     echo [ERROR] Local venv not found: "%%PY%%"
echo     echo.
echo     echo Create it with:
echo     echo   python -m venv "%%VENV_DIR%%"
echo     pause
echo     exit /b 1
echo ^)
echo.
echo title "%%PROJECT_NAME%% - SYNC"
echo.
echo echo ============================================================
echo echo  Syncing: %%PROJECT_NAME%%
echo echo  Python : %%PY%%
echo echo ============================================================
echo echo.
echo.
echo echo [1/3] Upgrading pip...
echo echo ============================================================
echo "%%PY%%" -m pip install --upgrade pip
echo echo.
echo.
echo if exist "requirements.txt" ^(
echo     echo [2/3] Installing from requirements.txt...
echo     echo ============================================================
echo     "%%PY%%" -m pip install -r requirements.txt
echo     echo.
echo ^) else ^(
echo     echo [2/3] SKIPPED: No requirements.txt found.
echo     echo       Create one with: pip.bat freeze ^> requirements.txt
echo     echo.
echo ^)
echo.
echo echo [3/3] Dependency health check...
echo echo ============================================================
echo "%%PY%%" -m pip check
echo echo.
echo.
echo echo ============================================================
echo echo  SYNC COMPLETE
echo echo ============================================================
echo pause
echo exit /b 0
) > sync.bat
    echo [OK]   sync.bat
)

rem ── shell.bat ────────────────────────────────────────────────
if exist "shell.bat" (
    echo [SKIP] shell.bat already exists
) else (
(
echo @echo off
echo cd /d "%%~dp0"
echo.
echo rem ============================================================
echo rem  Project venv shell
echo rem  Generated by setup.bat
echo rem ============================================================
echo.
echo set "PROJECT_NAME=%PROJECT_NAME%"
echo set "VENV_DIR=%VENV_DIR%"
echo set "ACTIVATE=%%CD%%\%%VENV_DIR%%\Scripts\activate.bat"
echo.
echo if not exist "%%ACTIVATE%%" ^(
echo     echo [ERROR] Local venv was not found:
echo     echo         "%%ACTIVATE%%"
echo     echo.
echo     echo Create it with:
echo     echo         python -m venv "%%VENV_DIR%%"
echo     echo.
echo     pause
echo     exit /b 1
echo ^)
echo.
echo title "%%PROJECT_NAME%% - VENV SHELL"
echo call "%%ACTIVATE%%"
echo.
echo echo ============================================================
echo echo  Project shell activated
echo echo  Project: "%%CD%%"
echo echo  Python :
echo where python
echo echo  Type "exit" to leave this shell.
echo echo ============================================================
echo echo.
echo cmd /k
) > shell.bat
    echo [OK]   shell.bat
)

rem ── test.bat ─────────────────────────────────────────────────
if exist "test.bat" (
    echo [SKIP] test.bat already exists
) else (
(
echo @echo off
echo setlocal
echo cd /d "%%~dp0"
echo.
echo rem ============================================================
echo rem  Project test runner
echo rem  Generated by setup.bat
echo rem.
echo rem  Usage:
echo rem    test.bat                        ^(run all tests^)
echo rem    test.bat tests/test_core.py     ^(run a specific file^)
echo rem    test.bat -k mapper              ^(filter by name^)
echo rem    test.bat -v --tb=short          ^(verbose with short tracebacks^)
echo rem ============================================================
echo.
echo set "PROJECT_NAME=%PROJECT_NAME%"
echo set "VENV_DIR=%VENV_DIR%"
echo set "PY=%%CD%%\%%VENV_DIR%%\Scripts\python.exe"
echo.
echo if not exist "%%PY%%" ^(
echo     echo [ERROR] Local venv was not found:
echo     echo         "%%PY%%"
echo     echo.
echo     pause
echo     exit /b 1
echo ^)
echo.
echo title "%%PROJECT_NAME%% - TEST"
echo echo ============================================================
echo echo  Testing: "%%PROJECT_NAME%%"
echo echo  Python : "%%PY%%"
echo echo ============================================================
echo echo.
echo "%%PY%%" -m pytest -v %%*
echo set "EXITCODE=%%ERRORLEVEL%%"
echo.
echo echo.
echo echo ============================================================
echo if "%%EXITCODE%%"=="0" ^(
echo     echo  TESTS PASSED
echo ^) else ^(
echo     echo  TESTS FAILED  ^^(exit code: %%EXITCODE%%^^)
echo ^)
echo echo ============================================================
echo pause
echo exit /b %%EXITCODE%%
) > test.bat
    echo [OK]   test.bat
)

rem ── doctor.bat ───────────────────────────────────────────────
if exist "doctor.bat" (
    echo [SKIP] doctor.bat already exists
) else (
(
echo @echo off
echo setlocal
echo cd /d "%%~dp0"
echo.
echo rem ============================================================
echo rem  Project Doctor
echo rem  Generated by setup.bat
echo rem ============================================================
echo.
echo set "PROJECT_NAME=%PROJECT_NAME%"
echo set "VENV_DIR=%VENV_DIR%"
echo set "ENTRY_MODE=%ENTRY_MODE%"
echo set "APP_ENTRY=%APP_ENTRY%"
echo set "RUNNER_ARGS=%RUNNER_ARGS%"
echo set "PY=%%CD%%\%%VENV_DIR%%\Scripts\python.exe"
echo.
echo echo ============================================================
echo echo  PROJECT DOCTOR: %%PROJECT_NAME%%
echo echo ============================================================
echo echo  Project : %%CD%%
echo echo  Mode    : %%ENTRY_MODE%%
echo echo  Entry   : %%APP_ENTRY%%
echo if /I "%%ENTRY_MODE%%"=="runner" echo  Args    : %%RUNNER_ARGS%%
echo echo.
echo.
echo if not exist "%%PY%%" ^(
echo     echo [FAIL] venv not found at: "%%PY%%"
echo     echo.
echo     echo Create it with:
echo     echo   python -m venv "%%VENV_DIR%%"
echo     pause
echo     exit /b 1
echo ^)
echo.
echo echo [OK] venv found: "%%PY%%"
echo echo.
echo.
echo echo ------------------------------------------------------------
echo echo  Python Environment
echo echo ------------------------------------------------------------
echo "%%PY%%" -c "import sys; print('Executable :', sys.executable); print('Version    :', sys.version.split()[0]); print('Prefix     :', sys.prefix)"
echo echo.
echo.
echo echo ------------------------------------------------------------
echo echo  pip version
echo echo ------------------------------------------------------------
echo "%%PY%%" -m pip --version
echo echo.
echo.
echo echo ------------------------------------------------------------
echo echo  Installed Packages
echo echo ------------------------------------------------------------
echo "%%PY%%" -m pip list
echo echo.
echo.
echo echo ------------------------------------------------------------
echo echo  Dependency Health
echo echo ------------------------------------------------------------
echo "%%PY%%" -m pip check
echo echo.
echo.
echo echo ------------------------------------------------------------
echo echo  Entry Point Check
echo echo ------------------------------------------------------------
echo if /I "%%ENTRY_MODE%%"=="file" ^(
echo     if exist "%%APP_ENTRY%%" ^(
echo         echo [OK] Entry file found: "%%APP_ENTRY%%"
echo     ^) else ^(
echo         echo [FAIL] Entry file NOT found: "%%APP_ENTRY%%"
echo     ^)
echo ^) else ^(
echo     "%%PY%%" -c "import importlib.util, sys; name=r'%%APP_ENTRY%%'; spec=importlib.util.find_spec^(name^); print^(^('[OK] Module found: ' if spec else '[FAIL] Module NOT found: '^) + name^); sys.exit^(0 if spec else 1^)" 2^>nul
echo     if errorlevel 1 echo [FAIL] Module import test failed.
echo     if /I "%%ENTRY_MODE%%"=="runner" echo [INFO] Runner args: "%%RUNNER_ARGS%%"
echo ^)
echo echo.
echo.
echo echo ------------------------------------------------------------
echo echo  Project Files
echo echo ------------------------------------------------------------
echo if exist "uv.lock"          echo [OK]   uv.lock found
echo if exist "pyproject.toml"   echo [OK]   pyproject.toml found
echo if exist "requirements.txt" echo [OK]   requirements.txt found
echo if not exist "requirements.txt" echo [WARN] requirements.txt missing
echo echo.
echo.
echo echo ============================================================
echo echo  DOCTOR COMPLETE
echo echo ============================================================
echo pause
echo exit /b 0
) > doctor.bat
    echo [OK]   doctor.bat
)

echo.
echo ============================================================
echo  SETUP COMPLETE
echo.
echo  Companion scripts are ready. You can delete any you don't
echo  need. They will NOT be regenerated if they already exist.
echo.
echo  Next steps:
echo    run.bat    - Launch %PROJECT_NAME%
echo    sync.bat   - Reinstall / update dependencies
echo    test.bat   - Run pytest suite
echo    shell.bat  - Open activated venv shell
echo    doctor.bat - Environment health check
echo    pip.bat    - Project-local pip wrapper
echo ============================================================
pause
exit /b 0
