@echo off
setlocal
cd /d "%~dp0"

rem ============================================================
rem  Dependency Sync (pip)
rem  Generated by Venv Batch Template Generator v3.3
rem  Generated on: 2026-06-21 23:54
rem ============================================================

set "PROJECT_NAME=creep"
set "VENV_DIR=.venv"
set "PY=%CD%\%VENV_DIR%\Scripts\python.exe"

if not exist "%PY%" (
    echo [ERROR] Local venv not found: "%PY%"
    echo.
    echo Create it with:
    echo   python -m venv "%VENV_DIR%"
    pause
    exit /b 1
)

title "%PROJECT_NAME% - SYNC"

echo ============================================================
echo  Syncing: %PROJECT_NAME%
echo  Python : %PY%
echo ============================================================
echo.

echo [1/3] Upgrading pip...
echo ============================================================
"%PY%" -m pip install --upgrade pip
echo.

if exist "requirements.txt" (
    echo [2/3] Installing from requirements.txt...
    echo ============================================================
    "%PY%" -m pip install -r requirements.txt
    echo.
) else (
    echo [2/3] SKIPPED: No requirements.txt found.
    echo       Create one with: pip.bat freeze ^> requirements.txt
    echo.
)

echo [3/3] Dependency health check...
echo ============================================================
"%PY%" -m pip check
echo.

echo ============================================================
echo  SYNC COMPLETE
echo ============================================================
pause
exit /b 0
