@echo off
setlocal
cd /d "%~dp0"

rem ============================================================
rem  Project test runner
rem  Generated by Venv Batch Template Generator v3.3
rem  Generated on: 2026-06-21 23:54
rem
rem  Runs pytest via the project-local venv Python.
rem
rem  Usage:
rem    test.bat                        (run all tests)
rem    test.bat tests/test_core.py     (run a specific file)
rem    test.bat -k mapper              (filter by name)
rem    test.bat -v --tb=short          (verbose with short tracebacks)
rem ============================================================

set "PROJECT_NAME=creep"
set "VENV_DIR=.venv"
set "PY=%CD%\%VENV_DIR%\Scripts\python.exe"

if not exist "%PY%" (
    echo [ERROR] Local venv was not found:
    echo         "%PY%"
    echo.
    pause
    exit /b 1
)

title "%PROJECT_NAME% - TEST"
echo ============================================================
echo  Testing: "%PROJECT_NAME%"
echo  Python : "%PY%"
echo ============================================================
echo.
"%PY%" -m pytest -v %*
set "EXITCODE=%ERRORLEVEL%"

echo.
echo ============================================================
if "%EXITCODE%"=="0" (
    echo  TESTS PASSED
) else (
    echo  TESTS FAILED  ^(exit code: %EXITCODE%^)
)
echo ============================================================
pause
exit /b %EXITCODE%
